@startuml

left to right direction
title Diagrama de Casos de Uso - Sistema de Cadastro de Alunos


skinparam packageStyle rectangle

skinparam actorBorderColor #191139
skinparam actorFontStyle bold


skinparam usecaseBorderColor #191139
skinparam usecaseFontSize 15
skinparam usecaseFontStyle bold
skinparam usecaseBackgroundColor #E0D8C2

skinparam packageBorderColor #191139
skinparam packageFontSize 15
skinparam packageFontStyle bold


skinparam arrowThickness 1.5
skinparam arrowFontColor #607D8B
skinparam arrowFontSize 14 


actor Funcionario
actor Administrador
actor Professor

Administrador --|> Funcionario


package "Autenticação e Acesso" {
  usecase "Autenticar-se no Sistema" as UC_AutenticarNoSistema
  usecase "Realizar Logout" as UC_RealizarLogout
}

package "Administração do Sistema" {
  usecase "Cadastrar Novo Funcionário" as UC_CadastrarFuncionario
  usecase "Consultar Funcionários" as UC_ListarFuncionarios
  usecase "Atualizar Dados de Funcionário" as UC_AtualizarFuncionario
  usecase "Excluir Funcionário" as UC_ExcluirFuncionario
}

package "Gestão de Alunos" {
  usecase "Cadastrar Novo Aluno" as UC_CadastrarAluno
  usecase "Consultar Alunos" as UC_ListarAlunos
  usecase "Atualizar Dados de Aluno" as UC_AtualizarDadosAlunoPorFunc
  usecase "Excluir Aluno" as UC_ExcluirAluno
  usecase "Matricular Aluno em Curso" as UC_MatricularAlunoEmCurso
  usecase "Atualizar Status de Matrícula" as UC_AtualizarStatusMatricula
  usecase "Aluno Atualiza Próprios Dados" as UC_AlunoAtualizaPropriosDados
}

package "Gestão de Cursos" {
  usecase "Cadastrar Novo Curso" as UC_CadastrarCurso
  usecase "Consultar Cursos" as UC_ListarCursos
  usecase "Atualizar Dados de Curso" as UC_AtualizarDadosCurso
  usecase "Excluir Curso" as UC_ExcluirCurso
  usecase "Associar Professor a Curso" as UC_AssociarProfessorAoCurso
}

package "Registro de Notas" {
  usecase "Registrar Nota" as UC_RegistrarNota
  usecase "Atualizar Nota" as UC_AtualizarNota
}

package "Consultas e Histórico Acadêmico" {
  usecase "Consultar Histórico Acadêmico de Aluno" as UC_FuncConsultarHistoricoAluno
  usecase "Consultar Notas de Aluno" as UC_FuncConsultarNotasAluno
  usecase "Consultar Próprio Histórico Acadêmico" as UC_AlunoConsultarProprioHistorico
  usecase "Consultar Próprias Notas" as UC_AlunoConsultarPropriasNotas
  usecase "Consultar Notas de Alunos em Seus Cursos" as UC_ProfConsultarNotasAlunosCursos
  usecase "Consultar Lista de Alunos em Seus Cursos" as UC_ProfConsultarListaAlunosCursos
}


Funcionario -- UC_AutenticarNoSistema
Funcionario -- UC_RealizarLogout
Professor -- UC_AutenticarNoSistema
Professor -- UC_RealizarLogout

Administrador -- UC_CadastrarFuncionario
Administrador -- UC_ListarFuncionarios
Administrador -- UC_AtualizarFuncionario
Administrador -- UC_ExcluirFuncionario

Funcionario -- UC_CadastrarAluno
Funcionario -- UC_ListarAlunos
Funcionario -- UC_AtualizarDadosAlunoPorFunc
Funcionario -- UC_ExcluirAluno
Funcionario -- UC_MatricularAlunoEmCurso
Funcionario -- UC_AtualizarStatusMatricula

Funcionario -- UC_CadastrarCurso
Funcionario -- UC_ListarCursos
Funcionario -- UC_AtualizarDadosCurso
Funcionario -- UC_ExcluirCurso
Funcionario -- UC_AssociarProfessorAoCurso

Professor -- UC_RegistrarNota
Professor -- UC_AtualizarNota

Funcionario -- UC_FuncConsultarHistoricoAluno
Funcionario -- UC_FuncConsultarNotasAluno
Professor -- UC_ProfConsultarNotasAlunosCursos
Professor -- UC_ProfConsultarListaAlunosCursos


actor Aluno


UC_AutenticarNoSistema -- Aluno
UC_RealizarLogout -- Aluno
UC_AlunoAtualizaPropriosDados -- Aluno
UC_AlunoConsultarProprioHistorico -- Aluno
UC_AlunoConsultarPropriasNotas -- Aluno

@enduml