@startuml
title Processo de Negócio: Cadastro de Novo Aluno

skinparam defaultFontName Segoe UI
skinparam defaultFontSize 12
skinparam activityBorderColor #616161
skinparam activityBackgroundColor #FAFAFA
skinparam activityDiamondBorderColor #616161
skinparam activityDiamondBackgroundColor #FAFAFA
skinparam arrowColor #424242
skinparam noteBackgroundColor #FFFFE0
skinparam noteBorderColor #B0A070
skinparam shadowing true

partition "Funcionário" #E0F2F7 {
  start
  :Preencher Formulário de Cadastro do Aluno;
  :Submeter Formulário para o Sistema;
}

partition "Sistema Académico" #FFF9E6 {
  :Receber Dados do Formulário Submetido;
  :Validar Dados do Aluno;

  if (Dados do Aluno são Válidos?) then (Sim)
    :Criar Registo de Aluno;
    :Persistir Dados do Aluno no Banco de Dados;
    :Gerar Confirmação de Cadastro;
    :Enviar Notificação de Sucesso para Funcionário;
  else (Não)
    :Registar Motivo da Falha na Validação;
    :Enviar Notificação de Falha para Funcionário ;
  endif
}

partition "Funcionário" #E0F2F7 {
  :Receber Notificação do Sistema;
  if (Cadastro Realizado com Sucesso?) then (Sim)
    :Visualizar Confirmação e Dados do Aluno Cadastrado;
    stop
  else (Não)
    :Visualizar Mensagem de Erro e Motivo da Falha;

    stop
  endif
}

@enduml